development:
  adapter: postgresql
  database: spree2_development
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: spree2_test
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: spree2_production
  encoding: unicode
  pool: 5
  timeout: 5000
