development:
  adapter: postgresql
  database: spreshop_development
  encoding: unicode
  user: spreeshop
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: spreeshop_test
  encoding: unicode
  user: spreeshop
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: spreeshop_production
  encoding: unicode
  pool: 5
  timeout: 5000
